---
language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox

notifications:
  irc:
    channels:
      - "irc.freenode.org##python-code-quality"
    use_notice: true
    skip_join: true
